name: CustomTags
main: customtags\darealaqua\Main
author: DaRealAqua
api: 5.0.0
version: 0.0.5+dev
description: A Custom Tags plugin made with love by DaRealAqua
website: discord.levania.eu
depend:
  - EconomyAPI

permissions:
  customtags.use:
    description: Use Tags On Chat
    default: true
